ARCHCNL-2: Rename test (GWT pattern)
Mari-Wie/ArchCNL pull request #181
Opened 2021-07-21 15:15 UTC by cmkehler

After the previously mentioned problems (Locally everything works find, in the github build chain I get failing test), I made a new branch and redid the work from scratch. In the meantime there were also a couple of new tests that I also renamed according to the given-when-then pattern.

2021-07-24 14:04 UTC, VincentRaudszus requested changes
The changes seem fine but I noticed some violations of the Google Code Style in form of lines with more than 100 symbols. This will cause the pipeline to fail when we reactivate the spotless plugin and thus should be fixed.

2021-07-28 20:34 UTC, VincentRaudszus requested changes
Looks like it fulfills the style guide at first glance. However, the spotless plugin can be quite picky and is now reenabled on the master branch. So to ensure a smooth merge I would like you to do a final rebase on the master so that we can see whether the spotless plugin likes the changes as well.

2021-08-09 11:05 UTC, cmkehler commented
Finally applied all spotless changes, rebased with master (resulting in all of the commits) and fixed merge conflicts.

2021-08-11 12:29 UTC, VincentRaudszus approved these changes

2021-08-11 12:30 UTC, merged