Feature/microservice architecture templates
Mari-Wie/ArchCNL pull request #274
Opened 2022-02-16 07:15 UTC by HendrikZe

This introduces functionality behind the menu option "Import Rule Presets".
As an example the Micorservice Architecture has been used to introduce rule/mapping templates so that the user does not need to create the rules/mappings from scratch. The user is guided through a dialog where in the end, after entering a couple of different information on the application that the conformance check should be performed on, rules and mappings are created. 

Note: Wiki pages will be added in the next days.

2022-02-16 12:52 UTC, VincentRaudszus requested changes
Looks good overall but three listeners need to be added back to the MainPresenter.
Also, importing the _Layered Architecture_ Preset seems to have no effect. Is this intentional?

2022-02-16 12:52 UTC, VincentRaudszus commented on web-ui/src/main/java/org/archcnl/ui/MainPresenter.java
> -        inputPresenter.addListener(DeleteRelationRequestedEvent.class, this::handleEvent);
These three listeners need to be added back. They were recently introduced in [PR 272](https://github.com/Mari-Wie/ArchCNL/pull/272).

2022-02-16 12:52 UTC, VincentRaudszus commented on web-ui/src/main/java/org/archcnl/ui/MainPresenter.java
> -    }
Like the listeners the handling methods must also not be removed.

2022-02-16 14:03 UTC, VincentRaudszus approved these changes

2022-02-16 14:03 UTC, merged

2022-02-16 15:05 UTC, HendrikZe commented
@VincentRaudszus Layered Architecture is intentional. However, I agree that this is a bit misleading. I could add some rules for that style as well so that the dialog is behaving as intended (at the moment there are no rules after selecting the style) + preventing the user to be able to create Rules & Mappings (in the last step) by e.g. showing a notification that this style has no templates pre-defined.

Other solution would be to remove the layered architecture and open an issue on this so it can be added in the future. What do you think?

2022-02-17 09:05 UTC, VincentRaudszus commented
If you could add some rules and the notification like in the first option that would be perfect. That way it would be clear to every user that further presets will follow in that menu. However, I do not want to ask anything of you that would impact your remaining thesis work.